#%RAML 1.0 Library
uses:
  Link: ../annotation/Link.raml

types:

  DataStructureComponent:
    description: The role of the Represented Variable in the context of a Data Structure.

    properties:
      shortName:
        type: string
        description: A short technical name in CAPITAL LETTERS. Use underscore as word separator (no other special characters allowed).
        displayName: Short name

      format?:
        type: string
        description: This attribute describes the data-format of the component. For example a date-format.
        displayName: Format

      geoType?:
        type: string
        description: If the component is a geolocation then there are different types
        displayName: Geo type
        enum:
          - POINT
          - POLYGON
          - LINE

      # COMMENT:
      # Due to a practical need to link the InstanceVariable object more directly to the
      # StructurComponent object (IdentifierComponent, MeasureComponent or AttributeComponent),
      # the link from the DataStructureComponent to the RepresentedVariable is moved to
      # the InstanceVariable object in the (this) physical model. This is an alternative linking
      # that should be compatible with the link in the logical data model (LDS).
      # representedVariable:
      #   type: string
      #   displayName: Represented variable
      #   (Link.types): [RepresentedVariable]
