#%RAML 1.0 Library
uses:
  MultilingualText: ./MultilingualText.raml

types:

  PropertyTranslation:
    description: A reusable type for language translations on domain properties
    displayName: Property translation
    type: object

    properties:
      nameTranslations?:
        type: MultilingualText.MultilingualText[]
        description: Name translations for this property
        displayName: Name translations

      descriptionTranslations?:
        type: MultilingualText.MultilingualText[]
        description: Description translations for this property
        displayName: Description translations

      propertyName:
        type: string
        description: Name of the property
        displayName: Property name