kind: pipeline
name: gsim-raml-schema

steps:
  - name: authenticate
    image: robertstettner/drone-mvn-auth
    pull: always
    settings:
      servers:
        from_secret: maven_servers

  - name: build
    image: maven:3-jdk-8-slim
    commands:
      - ls -lah
      - mvn dependency:get -DartifactId=no.ssb.raml:raml-to-jsonschema:0.15-20191004.100316-1:jar -DremoteRepositories=https://nexus.prod-bip-ci.ssb.no/repository/maven-snapshots/ -Ddest=/ --global-settings settings.xml
      - ls -lah
    when:
      event:
      - push
      branch:
      - devtest

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
#      channel: bip-ci-test -- Choosing channel is not enabled yet
      template: >
        {{#success build.status}}
          *Success*! {{uppercasefirst build.event}} - {{build.link}}. Good job *{{build.author}}*!
        {{else}}
          *Failure*! {{uppercasefirst build.event}} - {{build.link}}. Your fault *{{build.author}}*!
        {{/success}}
    when:
      status: [ success, failure ]

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url