kind: pipeline
name: default

steps:

  - name: test
    image: quay.io/testcontainers/dind-drone-plugin
    build_image: openjdk:8-jdk
    cmd: java -v
      -
      - sleep 5
      - docker ps
      - docker run -v $(pwd):/raml-project statisticsnorway/raml-to-jsonschema
    when:
      event:
        exclude:
        - pull_request
      branch:
      - devtest
