kind: pipeline
name: gsim-raml-schema

steps:
  - name: prepare
    image: docker:git
    commands:
      - git clone https://github.com/statisticsnorway/raml-to-jsonschema.git
    when:
      event:
      - pull_request
      - push

  - name: build
    image: maven:3-jdk-8-slim
    commands:
      - mvn -f /raml-to-jsonchema/pom.xml clean package
      - java -jar /raml-to-jsonchema/raml-to-jsonschema-0.15-SNAPSHOT-shaded.jar /drone/src/out /drone/src/schemas
      - ls -lah /drone/src/out
    when:
      event:
      - pull_request
      - push

#  - name: publish-docker
#    image: plugins/gcr
#    settings:
#      repo: prod-bip/lds-postgres-gsim
#      registry: eu.gcr.io
#      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
#      json_key:
#        from_secret: gcr_credentials
#    when:
#      branch:
#        - master
#      event:
#        - push

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook:
#        from_secret: slack_webhook_url
#      channel: bip-ci-test -- Choosing channel is not enabled yet
#      template: >
#        {{#success build.status}}
#          *Success*! {{uppercasefirst build.event}} - {{build.link}}. Good job *{{build.author}}*!
#        {{else}}
#          *Failure*! {{uppercasefirst build.event}} - {{build.link}}. Your fault *{{build.author}}*!
#        {{/success}}
#    when:
#      status: [ success, failure ]

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url