kind: pipeline
name: gsim-raml-schema

steps:
  - name: build
    image: docker
    commands:
      - ls -lah
      - docker run -v /:/raml-project statisticsnorway/raml-to-jsonschema:latest
    when:
      event:
      - push
      branch:
      - devtest