kind: pipeline
name: gsim-raml-schema

steps:
  - name: build
    image: plugins/docker
    commands:
      - ls -lah
      - sudo service docker status
#      - docker run -v $(pwd):/raml-project statisticsnorway/raml-to-jsonschema:latest
    when:
      event:
      - push
      branch:
      - devtest

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
#      channel: bip-ci-test -- Choosing channel is not enabled yet
      template: >
        {{#success build.status}}
          *Success*! {{uppercasefirst build.event}} - {{build.link}}. Good job *{{build.author}}*!
        {{else}}
          *Failure*! {{uppercasefirst build.event}} - {{build.link}}. Your fault *{{build.author}}*!
        {{/success}}
    when:
      status: [ success, failure ]

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url