kind: pipeline
name: default

steps:

  - name: build
    image: docker:stable-dind
    privileged: true
    commands:
      #privileged: true
      - docker -v
      - docker run -v $(pwd):/raml-project statisticsnorway/raml-to-jsonschema
    when:
      event:
        exclude:
        - pull_request
      branch:
      - devtest
    volumes:
      - name: docker_run
        path: /var/run/
      - name: docker_lib
        path:  /var/lib/docker
