kind: pipeline
name: default

steps:

  - name: test
    image: docker:19.03-dind
    #privileged: true
    #environment:
    #  - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 20
      - docker ps
      - docker run -v $(pwd):/raml-project statisticsnorway/raml-to-jsonschema
    when:
      event:
        exclude:
        - pull_request
      branch:
      - devtest
