#%RAML 1.0 Library
#Defines links between attributes and objects
annotationTypes:
  types:
    type: string[]
    description: Holds the type of objects a link points to

  pagination:
    type: boolean
    description: If the link should use pagination

  reverseName:
    type: string
    description: Name of reverse link
