uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  StatisticalUnit:
    description: An actor that performs a role in relation to the statistical Business Process.
    displayName: Agent
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
