#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

  # COMMENT:
  # XML example:
  #   <address>
  #     <street>Hollywood Blvd</street>
  #     <zipCode>90027</zipCode>
  #     <city>Los Angeles, CA</city>
  #   </adresse>
  # GSIM ComponentRelationship example:
  #   ComponentRelationship.target = "address"
  #   ComponentRelationship.soruce = ["street", "zipCode", "city"]

types:

  ComponentRelationship:
    description: This reflects that there could be a structure within the Logical Record, for example several fields can together represent a structured field (e.g. an address), or the record can be structured as in the case of an XML file conformant to a schema.
    displayName: Component relationship
    type: [ IdentifiableArtefact.IdentifiableArtefact ]

    properties:
      targetComponent:
        type: string
        description: The relation target component, e.g. "address"
        displayName: Target component
        (Link.types): [IdentifierComponent, MeasureComponent, AttributeComponent]

      sourceComponents:
        type: string[]
        description: The relation source component(s), e.g. "street", "zipCode" and "city".
        displayName: Source components
        (Link.types): [IdentifierComponent, MeasureComponent, AttributeComponent]

    example: !include ../examples/_main/ComponentRelationship_DataQuality_NumOfChildren.json
