#%RAML 1.0 Library
types:
  ContactInfo:
    description: Contact information for a person
    displayName: Contact information

    properties:
      name:
        type: string
        description: name of person
        displayName: name

      phone:
        type: string
        description: The full phone number of the person
        displayName: phone number

      email:
        type: string
        description: the full e-mail of the person
        displayName: e-mail
