#%RAML 1.0 Library
types:
  ContactInfo:
    description: A code reference in a subset of classifications
    displayName: Classification code
    type: [ ]

    properties:
      name:
        type: string
        description: name of person
        displayName: name

      phone:
        type: string
        description: The full phone number of the person
        displayName: phone number

      email:
        type: string
        description: the full e-mail of the person
        displayName: e-mail
