#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ExchangeChannel: ./abstract/ExchangeChannel.raml

types:
  DataHarvester:
    description: A concrete and usable tool to gather information from the Internet.
    displayName: DataHarvester
    type: [ IdentifiableArtefact.IdentifiableArtefact, ExchangeChannel.ExchangeChannel ]

    properties:
      dataHarvesterType:
        type: string
        description: Method for harvesting data
        displayName: Data harvester type
        enum:
          - API
          - WEBSCRAPING
          


  example: !include ../examples/_main/DataHarvester_ShipRegisterNISNOR.json
