#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ExchangeChannel: ./abstract/ExchangeChannel.raml

types:
  DataHarvester:
    description: A concrete and usable tool to gather information from the Internet.
    displayName: DataHarvester
    type: [ IdentifiableArtefact.IdentifiableArtefact, ExchangeChannel.ExchangeChannel ]

    properties:
