#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  ExchangeChannel:
    description: A means of exchanging data.
    displayName: Exchange channel
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
      exchangeType:
        type: string
        description: Type of exchange Channels.
        displayName: Exchange type
        enum:
          - COLLECT
          - DISSEMINATE

      protocol:
        type: string
        displayName: Protocol
        (Link.types): [Protocol]

    example: !include ../examples/_main/ExchangeChannel_ShipRegisterNISNOR.json
