#%RAML 1.0 Library
uses:
  GsimObjectPropertyLanguageTranslation: ./abstract/GsimObjectPropertyLanguageTranslation.raml
  MultilingualText: ./abstract/MultilingualText.raml

types:

  GsimObjectLanguageTranslation:
    description: Assign multilingual text to the name and description of an object and its properties
    displayName: GSIM object language translation

    properties:
      id:
        type: string
        description: Identifies the domain, by name, that these language translations are for
        displayName: Id

      propertyTranslations?:
        type: GsimObjectPropertyLanguageTranslation.GsimObjectPropertyLanguageTranslation[]
        description: Language translations for the properties
        displayName: Property language translations

      domainNameTranslation?:
        type: MultilingualText.MultilingualText[]
        description: Language translation for the domain name
        displayName: Domain name language translation
        
      domainDescriptionTranslation?:
        type: MultilingualText.MultilingualText[]
        description: Language translation for the domain description
        displayName: Domain description language translation

    example: !include ../examples/_main/GsimObjectLanguageTranslation_Agent.json
