#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:

  InformationConsumer:
    description: A person or organization that consumes disseminated data.
    displayName: Information consumer
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
