#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  InstanceVariable:
    description: The use of a Represented Variable within a Data Set. It may include information about the source of the data.
    displayName: Instance variable
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
      representedVariable:
        type: string
        displayName: Represented variable
        (Link.relationLink):
          linksTo: [RepresentedVariable]
          pagination: SOURCE
          isReverseLink: true
          reverseLinkName: representedVariable_has_instanceVariables

      population:
        type: string
        displayName: Population
        (Link.relationLink):
          linksTo: [Population]
          pagination: NONE
          isReverseLink: false

      # COMMENT:
      # Due to a practical need to link the InstanceVariable object more directly to the
      # StructurComponent object (IdentifierComponent, MeasureComponent or AttributeComponent),
      # the (this) link between InstanceVariable and DataStructureComponent is created in addition
      # to the existing link between the DataStructureComponent and the RepresentedVariable
      # in the (this) physical model.
      dataStructureComponent:
          type: string
          displayName: Data Structure Component
          (Link.types): [IdentifierComponent, MeasureComponent, AttributeComponent]

      sentinelValueDomain?:
        type: string
        displayName: Sentinel value domain
        (Link.types): [EnumeratedValueDomain, DescribedValueDomain]

    example: !include ../examples/_main/InstanceVariable_FamilyType.json
