#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml


types:

  ProcessStepInstance:
    description: An executed step in a Business Process. A Process Step Instance specifies the actual inputs to and outputs from for an occurrence of a Process Step.
    displayName: Process step instance
    type: [ IdentifiableArtefact.IdentifiableArtefact]

    properties:
      parameterInput?:
        type: string
        displayName: Parameter input
        (Link.types): [ParameterInput]

      transformableInput?:
        type: string
        displayName: Transformable input
        (Link.types): [TransformableInput]

      processSupportInput?:
        type: string
        displayName: Process support input
        (Link.types): [ProcessSupportInput]

      transformedOutput?:
        type: string
        displayName: Transformed output
        (Link.types): [TransformedOutput]

      processMetric?:
        type: string
        displayName: Process metric
        (Link.types): [ProcessMetric]

      processExecutionLog?:
        type: string
        displayName: Process execution log
        (Link.types): [ProcessExecutionLog]

    #example: !include ../examples/ProcessStepInstance.json

