#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ProcessOutput: ./abstract/ProcessOutput.raml
types:

  TransformedOutput:
    description: A <i>Process Output</i> (a result) which provides the "reason for existence" for the <i>Process Step</i>.
    displayName: Transformed output
    type: [IdentifiableArtefact.IdentifiableArtefact, ProcessOutput.ProcessOutput]
    properties:

    #example: !include ../examples/TransformedOutput.json

